name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable


    - name: Run unit tests
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./coverage

    - name: Install FTP deployer
      run: npm install -g ftp-deploy

    - name: Deploy to FTP server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: ${{ secrets.FTP_HOST }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_path: './public'
        remote_path: '/'
        port: 22